---
title: "Facebook ADS"
author: "Ondrej Pekacek/TI CZ"
date: "Update `r format(Sys.time(),'%d. %m. %Y')`"
output: 
  flexdashboard::flex_dashboard:
    logo: "data/logo_ti.png"
    theme: readable
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/opop999/TI_monitoring_fb_political_ads_2022
    navbar:
      - {title: "Project", icon: "ion-information-circled", href: "https://www.transparentnivolby.cz/komunalni-senat2022/"}
      - {title: "Author", icon: "ion-social-linkedin", href: "https://www.linkedin.com/in/ondrej-pekacek"}
      - {title: "Data: META", icon: "ion-cloud", href: "https://www.facebook.com/ads/library/"}
---

```{r setup, include=FALSE}
# Disable scientific notation of numbers
options(scipen = 999)

# Package names
packages <- c("flexdashboard", "dplyr", "ggplot2", "plotly", "forcats", "htmlwidgets", "tidyr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Specify directory with datasets
directory_datasets <- "data/"

# Import datasets created in the previous script
summary_dataset <- readRDS(file = paste0(directory_datasets, "summary_tables/merged_summary.rds"))
time_dataset <- readRDS(file = paste0(directory_datasets, "summary_tables/time_summary.rds"))

# Select TOP 10 biggest spenders for plotting
top_10_spenders <- summary_dataset %>%
  slice_max(avg_spend, n = 10) %>%
  select(page_name, page_id, avg_spend)

# Election date for vertical line in the time-plots
election_date <- as.Date("2022-09-23")

# Graph zoom date end & beginning
start_date <- as.Date("2022-04-13")
end_date <- as.Date("2022-10-01")

```

Summaries
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **TOTAL ADS**

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(page_name = reorder(page_name, total_ads)) %>%
    ggplot(
      aes(
        x = total_ads,
        y = page_name,
        fill = percent_unique,
        text = paste(
          "Page:",
          page_name,
          "<br>Total ads:",
          total_ads,
          "<br>Proportion unique:",
          percent_unique * 100, "%"
        )
      )
    ) +
    geom_col() +
    scale_fill_gradient(
      low = "#fbe8e7",
      high = "#db1d0b",
      limits = c(0, 1),
      breaks = c(0, 0.25, 0.50, 0.75, 1),
      labels = c("0%", "25%", "50%", "75%", "100%")
    ) +
    scale_x_continuous(
      breaks = seq(0, 5000, 250),
      labels = seq(0, 5000, 250)
    ) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Total ads") +
    ylab(element_blank()) +
    labs(fill = "Proportion unique ads") +
    ggtitle(paste(
      "Total ads of top 50 spenders since",
      format(start_date, "%d.%m.%Y")
    )),
  tooltip = "text"
)

```

### **TOTAL SPENDING**

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(
      avg_spend_1000 = round(avg_spend / 1000, digits = 0),
      per_ad_avg_spend_1000 = round(per_ad_avg_spend / 1000, digits = 1),
      page_name = reorder(page_name, avg_spend)
    ) %>%
    ggplot(
      aes(x = avg_spend_1000, y = page_name, fill = per_ad_avg_spend_1000, text = paste(
          "Page:",
          page_name,
          "<br>Total spend:",
          avg_spend_1000,"thousand CZK",
          "<br>Per ad avg spend:",
          per_ad_avg_spend_1000, "thousand CZK"
        ))
    ) +
    geom_col() +
    scale_fill_gradient2(
      low = "#cddae5",
      mid = "#03457f",
      high = "#023766",
      midpoint = 25,
      limits = c(0, 50)
    ) +
    scale_x_continuous(
      breaks = seq(0, 5000, 250),
      labels = seq(0, 5000, 250)
    ) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Total spend (CZK thousands)") +
    ylab(element_blank()) +
    labs(fill = "Per ad (CZK thousands)") +
    ggtitle(paste(
      "Spending on ads of top 50 spenders since",
      format(start_date, "%d.%m.%Y")
    )), 
  tooltip = "text"
)

```

### **AD LENGTH** 

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(page_name = reorder(page_name, avg_words)) %>%
    ggplot(aes(
      x = avg_words, y = page_name,
      text = paste(
          "Page:",
          page_name,
          "<br>Avg length per ad:",
          avg_words, "words"
        )
    )) +
    geom_col(fill = "#320266") +
    scale_x_continuous(
      breaks = seq(0, 1500, 100),
      labels = seq(0, 1500, 100)
    ) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Number of Words") +
    ylab(element_blank()) +
    ggtitle(
      paste(
        "Average ad length in words of top 50 spenders since",
        format(start_date, "%d.%m.%Y")
      )
    ), 
  tooltip = "text"
)

```

### **AD RUNTIME** 

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(page_name = reorder(page_name, avg_ad_runtime)) %>%
    ggplot(aes(
      x = avg_ad_runtime, y = page_name, text = paste(
          "Page:",
          page_name,
          "<br>Avg runtime:",
          avg_ad_runtime, "days"
        ))
    ) +
    geom_col(fill = "#026663") +
    scale_x_continuous(breaks = seq(0, 150, 5),
                       labels = seq(0, 150, 5)) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Days") +
    ylab(element_blank()) +
    ggtitle(
      paste(
        "Average ad runtime of top 50 spenders since",
        format(start_date, "%d.%m.%Y")
      )
    ), 
  tooltip = "text"
)

```

### **IMPRESSIONS** 

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(
      avg_impressions_million = round(total_avg_impressions / 1000000, digits = 3),
      per_ad_avg_impressions_1000 = round(per_ad_avg_impression / 1000, digits = 1),
      page_name = reorder(page_name, avg_impressions_million)
    ) %>%
    ggplot(
      aes(x = avg_impressions_million, y = page_name, fill = per_ad_avg_impressions_1000,
          text = paste(
          "Page:",
          page_name,
          "<br>Total impressions:",
          avg_impressions_million, "million",
          "<br>Avg impressions per ad:",
          per_ad_avg_impressions_1000, "thousand"
        ))
    ) +
    geom_col() +
    scale_fill_gradient2(
      low = "#e7fbe8",
      mid = "#089914",
      high = "#011603",
      midpoint = 250,
      limits = c(0, 500)
    ) +
    scale_x_continuous(breaks = seq(0, 1000, 5),
                       labels = seq(0, 1000, 5)) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Total impressions (millions)") +
    ylab(element_blank()) +
    labs(fill = "Per Ad impressions (thousands)") +
    ggtitle(paste(
      "Total ads impressions of top 50 spenders since",
      format(start_date, "%d.%m.%Y")
    )), 
  tooltip = "text"
)

```

### **TOTAL MINIMAL AUDIENCE**

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(
      avg_min_reach_million = round(total_min_reach / 1000000, digits = 2),
      per_ad_avg_min_reach_1000 = round(per_ad_min_reach / 1000, digits = 0),
      page_name = reorder(page_name, avg_min_reach_million)
    ) %>%
    ggplot(
      aes(
        x = avg_min_reach_million,
        y = page_name,
        fill = per_ad_avg_min_reach_1000,
          text = paste(
          "Page:",
          page_name,
          "<br>Total minimum audience:",
          avg_min_reach_million, "million",
          "<br>Avg audience per ad:",
          per_ad_avg_min_reach_1000, "thousand"
        )
      )
    ) +
    geom_col() +
    scale_fill_gradient2(
      low = "#f0e6eb",
      mid = "#660237",
      high = "#14000b",
      midpoint = 1000,
      limits = c(0, 2000)
    ) +
    scale_x_continuous(breaks = seq(0, 5000, 50),
                 labels = seq(0, 5000, 50)) +
    theme_minimal() +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Total audience (millions)") +
    ylab(element_blank()) +
    labs(fill = "Per ad audience (thousands)") +
    ggtitle(
      paste(
        "Total minimal estimated audience of top 50 spenders since",
        format(start_date, "%d.%m.%Y")
      )
    ),
  tooltip = "text"
)
```

Trends
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **SPENDING OVER TIME**

```{r}
ggplotly(
  time_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    mutate(
      ad_creation_time_week = as.Date(cut(
        ad_creation_time,
        breaks = "week",
        start.on.monday = TRUE
      )),
      cumulative_spend_million = round((cumulative_spend / 1000000), digits = 3)
    ) %>%
    group_by(page_name, ad_creation_time_week) %>%
    summarise(end_of_week_million_spend = max(cumulative_spend_million)) %>%
    ungroup() %>%
    ggplot(
      aes(x = ad_creation_time_week, y = end_of_week_million_spend, color = page_name)
    ) +
    geom_line() +
    geom_point(size = 0.8, aes(text = paste(
          "Page:",
          page_name,
          "<br>Week:",
          ad_creation_time_week,
          "<br>Cumulative spend:",
          end_of_week_million_spend, "million CZK"
        ))) +
    geom_vline(
      aes(xintercept = as.numeric(election_date)),
      color = "#563a3a",
      linetype = 2,
      size = 0.2
    ) +
    geom_text(
      aes(x = election_date, y = 0, label = "elections"),
      color = "#22209F",
      vjust = -1,
      size = 3,
      fontface = "bold",
      check_overlap = TRUE
    ) +
    theme_minimal() +
    scale_y_continuous(breaks = seq(0, 5, 0.25),
                       labels = seq(0, 5, 0.25)) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(
      legend.title = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1)
    ) +
    xlab(element_blank()) +
    ylab("CZK million") +
    labs(color = "") +
    ggtitle(paste(
      "Spending on ads of top 10 spenders since",
      format(start_date, "%d.%m.%Y")
    )),
  tooltip = "text"
)

```

### **SPENDING WEEKLY**

```{r}
ggplotly(
  time_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    mutate(
      end_of_week = as.Date(cut(ad_creation_time, breaks = "week", start.on.monday = TRUE)),
    ) %>%
    group_by(page_name, end_of_week) %>% 
    summarise(by_week_thousands_spend = round(sum(avg_spend) / 1000, digits = 0)) %>% 
    ungroup() %>% 
    ggplot(aes(x = end_of_week, y = by_week_thousands_spend, fill = page_name, 
          text = paste(
          "Page:",
          page_name,
          "<br>Week:",
          end_of_week,
          "<br>Weekly spend:",
          by_week_thousands_spend, "thousand CZK"
        ))) +
    geom_col(width = 5.5) +
    geom_vline(xintercept = as.numeric(election_date), color = "#563a3a", linetype = 2, size = 0.2) +
    geom_text(aes(x = election_date, y = 0, label = "elections"), color = "#22209F", vjust = -1, size = 3, fontface = "bold", check_overlap = TRUE) +
    theme_minimal() +
    scale_y_continuous(
      breaks = seq(0, 5000, 200),
      labels = seq(0, 5000, 200)
    ) +
    scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") +
    coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) +
    theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) +
    xlab(element_blank()) +
    ylab("CZK thousand") +
  	labs(fill = "") +
    ggtitle(paste("Weekly spending on ads of top 10 spenders since", format(start_date, "%d.%m.%Y"))),
  tooltip = "text"
)

```

Demographics
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **GENDER**

```{r}
ggplotly(
  summary_dataset %>%
    filter(total_ads > 10) %>%
    slice_max(avg_spend, n = 50) %>%
    mutate(page_name = reorder(page_name, avg_male)) %>% 
    ggplot(aes(x = avg_male, y = page_name, fill = avg_male, text = paste(
          "Page:",
          page_name,
          "<br>Proportion of male audience:",
          avg_male * 100, "%"
        )
               )) +
    geom_col() +
    geom_vline(aes(xintercept = 0.5, color = "#db0b50")) +
    scale_fill_gradient(
      low = "#db1d0b", high = "#03457f",
    ) +
    scale_x_continuous(
      limits = c(0, 1),
      breaks = seq(0, 1, 0.25),
      labels = c("0%", "25%", "50%", "75%", "100%"),
      expand = c(0, 0)
    ) +
    theme_minimal() +
    theme(legend.position = "none") +
    theme(axis.text.y = element_text(size = 4.5)) +
    xlab("Proportion of ads targeting male audience") +
    ylab(element_blank()) +
    ggtitle(paste("Gender targeting of top 50 spenders since", format(start_date, "%d.%m.%Y"))),
  tooltip = "text"
)

```

### **AGE**

```{r}
ggplotly(
  summary_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    select(
      page_name,
      avg_18_24,
      avg_25_34,
      avg_35_44,
      avg_45_54,
      avg_55_64,
      avg_65_plus
    ) %>%
    pivot_longer(cols = 2:7, names_to = "age_group", values_to = "proportion", values_drop_na = TRUE) %>%
    ggplot(aes(x = age_group, y = proportion, fill = page_name, text = paste(
          "Page:",
          page_name,
          "<br>Proportion:",
          proportion * 100, "% (out of 100 %)"
        ))) +
    geom_col(position = "dodge2") +
    scale_x_discrete(labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")) +
    scale_fill_brewer(palette = "Paired") +
    scale_y_continuous(
      limits = c(0, 0.5),
      breaks = seq(0, 0.5, 0.1),
      labels = c("0%", "10%", "20%", "30%", "40%", "50%")
    ) +
    theme_minimal() +
    theme(legend.title = element_blank()) +
    xlab(element_blank()) +
    ylab(element_blank()) +
  	labs(fill = "") +
    ggtitle(paste("Age of audience of top 10 spenders since", format(start_date, "%d.%m.%Y"))),
  tooltip = "text"
)

```


### **REGION**

```{r}
ggplotly(
  summary_dataset %>%
    filter(page_id %in% top_10_spenders$page_id) %>%
    select(
      page_name,
      avg_pha,
      avg_stc,
      avg_jhc,
      avg_plk,
      avg_kvk,
      avg_ulk,
      avg_lbk,
      avg_hkk,
      avg_pak,
      avg_vys,
      avg_jhm,
      avg_olk,
      avg_msk,
      avg_zlk
    ) %>%
    pivot_longer(cols = 2:15, names_to = "region_group", values_to = "proportion", values_drop_na = TRUE) %>%
    ggplot(aes(x = region_group, y = proportion, fill = page_name, text = paste(
          "Page:",
          page_name,
          "<br>Proportion:",
          proportion * 100, "% (out of 100 %)"
        ))) +
    geom_col(position = "dodge2") +
    scale_x_discrete(labels = c("HKK", "JHC", "JHM", "KVK", "LBK", "MSK", "OLK", "PAK", "PHA", "PLK", "STC", "ULK", "VYS", "ZLK")) +
    scale_fill_brewer(palette = "Paired") +
    scale_y_continuous(
      limits = c(0, 0.5),
      breaks = seq(0, 0.5, 0.1),
      labels = c("0%", "10%", "20%", "30%", "40%", "50%")
    ) +
    theme_minimal() +
    theme(legend.title = element_blank()) +
    xlab(element_blank()) +
    ylab(element_blank()) +
  	labs(fill = "") +
    ggtitle(paste("Regions of audience of ads of top 10 spenders since", format(start_date, "%d.%m.%Y"))),
  tooltip = "text"
)

```


